spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    password: "dev"
  flyway:
    password: "dev"
admin:
  url: "jdbc:postgresql://localhost:5432/postgres"
  #Password: dev
  password: "$2a$10$v57rk18UIta5zcVpisbEyuMUl9ejw6L5.8y3QHAbKKgMoRPSLdtaC"