server:
  port: 5000
  servlet.context-path: "/"
  forward-headers-strategy: NATIVE #Allow to transfer X-Forwarded-For header
management:
  endpoints.web.exposure.include: "*"
spring:
  profiles.active: "appinfo"
  datasource:
    url: "jdbc:postgresql://deer-vision-db:5432/postgres"
    driverClassName: "org.postgresql.Driver"
    username: "postgres"
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    url: "jdbc:postgresql://deer-vision-db:5432/postgres"
    user: "postgres"
    password: ${DB_PASSWORD}
    locations: "classpath:db/migration"
  jpa:
    hibernate.ddl-auto: "none"
    show-sql: false
    open-in-view: false
  servlet.multipart:
    maxFileSize: 1073741824
    maxRequestSize: 1073741824
admin:
  password: ${ADMIN_PASSWORD}
  jwt-secret: ${ADMIN_JWT_SECRET}
  allowed-origins: "http://127.0.0.1:3000, http://localhost:3000, https://deervision.studio, https://www.deervision.studio"
app:
  version-pattern: "^\\d+[.]\\d+[.]\\d+(-snapshot)?$"
