server:
  port: 5000
  servlet.context-path: "/"
management:
  endpoints.web.exposure.include: "*"
spring:
  profiles.active: "appinfo"
  datasource:
    url: "jdbc:postgresql://localhost:5432/mytest"
    driverClassName: "org.postgresql.Driver"
    username: "postgres"
    password: "mysecretpassword"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL95Dialect"
    hibernate.ddl-auto: "update"
    show-sql: false
    open-in-view: false
  servlet.multipart:
    maxFileSize: 1073741824
    maxRequestSize: 1073741824
actuator:
  password: "$2a$10$LP.C2c/pkgWQE2Z5x9JNNejYbh1lJ81au58xoUZa5ZnWh/4ROITfu"
admin:
  password: "$2a$10$SRSz7BSfnjvUnX7/BJyLSufHJOS5z6mDvo4lzeQkVUdYqGYtEx2UG"
  jwt-secret: "zDARQgTBuU89Vdcqgw3wYGNUPFfv4BwuTWn6cRCcvEJSax6u98Ua8xzk5m7Z46cxnKZerM"
  allowed-origins: "http://127.0.0.1:3000, http://localhost:3000, https://deervision.studio"
app:
  version-pattern: "^\\d+[.]\\d+[.]\\d+(-snapshot)?$"
