- name: Add environment variable for database password
  lineinfile:
    path: /etc/environment
    regexp: '^DEER_VISION_DB_PASSWORD='
    line: "DEER_VISION_DB_PASSWORD={{ db_password }}"
    create: yes
  notify: Refresh environment

- name: Add environment variable for admin password
  lineinfile:
    path: /etc/environment
    regexp: '^DEER_VISION_ADMIN_PASSWORD='
    line: "DEER_VISION_ADMIN_PASSWORD={{ admin_password }}"
    create: yes
  notify: Refresh environment

- name: Add environment variable for admin JWT secret
  lineinfile:
    path: /etc/environment
    regexp: '^DEER_VISION_ADMIN_JWT_SECRET='
    line: "DEER_VISION_ADMIN_JWT_SECRET={{ admin_jwt_secret }}"
    create: yes
  notify: Refresh environment