- name: Ensure database directory exists
  file:
    path: "{{ db_dir }}"
    state: directory
    mode: '0755'
    owner: greg
    group: greg

- name: Run PostgreSQL container
  community.docker.docker_container:
    name: deer-vision-db
    image: postgres:17.6
    restart_policy: always
    env:
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - "{{ db_dir }}:/var/lib/postgresql/data"
    published_ports:
      - "13001:5432"
    detach: true

- name: Wait for container to initialize volume
  wait_for:
    path: "{{ db_dir }}"
    state: present
    timeout: 30

- name: Ensure permissions for DB directory
  file:
    path: "{{ db_dir }}"
    recurse: yes
    mode: '0755'

- name: Schedule database backup
  template:
    src: deer-vision-db-backup.j2
    dest: /etc/cron.daily/deer-vision-db-backup
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
