version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app/

permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ubuntu