name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Build JAR
        run: mvn -B clean package --file ./deer-vision-backend/pom.xml

      - name: Build and Push Docker image
        run: |
          docker build --build-arg JAR_FILE=deer-vision-backend/target/*.jar -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest .
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
