name: CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Build JAR
        if: github.ref == 'refs/heads/master'
        run: mvn -B clean package --file ./deer-vision-backend/pom.xml

      - name: Build and Push Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          cd ./deer-vision-backend/
          APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ./deploy/
          cp ../target/deer-vision*.jar ./deer-vision.jar
          docker build -t deer-vision .
          docker push ghcr.io/${{ github.repository_owner }}/deer-vision-backend:$APP_VERSION
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
