name: Pipeline Backend

on:
  push:
    branches:
      - '**'

env:
  APP_NAME: 'deervision'
  APP_JAR_START_NAME: 'deer-vision'
  APP_FOLDER: 'deer-vision-backend'

jobs:
  ci-backend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT on AWS
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Build JAR
        run: |
          cd ./${{ env.APP_FOLDER }}/
          mvn -B clean package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::496124100072:role/${{ env.APP_NAME }}GitHubAction
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.APP_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ./${{ env.APP_FOLDER }}/
          APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ./deploy/
          cp ../target/${{ env.APP_JAR_START_NAME }}*.jar ./${{ env.APP_JAR_START_NAME }}.jar
          docker build -t $REGISTRY/$REPOSITORY:$APP_VERSION .
          docker push $REGISTRY/$REPOSITORY:$APP_VERSION

  cd-backend:
    needs: ci-backend
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::496124100072:role/${{ env.APP_NAME }}GitHubAction
          aws-region: eu-central-1

      - name: Set Up SSH key
        run: echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy Docker Image On Instance
        run: |
          cd ./${{ env.APP_FOLDER }}/deploy/
          INSTANCE_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${{ env.APP_NAME }}Instance" --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          ssh -i ~/.ssh/id_rsa ubuntu@$INSTANCE_IP 'bash -s' < deploy-backend.sh